# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30, verbose_name='车牌号')),
                ('dispatch_date', models.DateField(verbose_name='发车日期')),
                ('origin', models.CharField(max_length=256, verbose_name='发出地')),
                ('destination', models.CharField(max_length=256, verbose_name='到达地')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='司机姓名')),
                ('identity_number', models.CharField(max_length=256, verbose_name='身份证号')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('license', models.CharField(max_length=256, verbose_name='驾照号')),
            ],
        ),
    ]
