# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='comments',
            field=models.CharField(max_length=800, null=True, verbose_name='备注'),
        ),
    ]
