# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatch', '0002_dispatchrecord_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
