# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dispatch', '0003_dispatchrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dispatch.Driver'),
        ),
    ]
