# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=256, verbose_name='账号名')),
                ('bank', models.CharField(max_length=256, verbose_name='开户银行')),
                ('account_number', models.IntegerField(verbose_name='账号')),
                ('card_holder', models.CharField(max_length=256, verbose_name='持卡人')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256, verbose_name='客户名')),
                ('contact_person', models.CharField(max_length=256, verbose_name='联系人')),
                ('contact_number', models.CharField(max_length=256, verbose_name='联系电话')),
                ('identity_number', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('gender', models.BooleanField(verbose_name='性别')),
                ('address', models.CharField(max_length=18, verbose_name='地址')),
                ('comments', models.CharField(max_length=18, verbose_name='备注')),
                ('payable', models.FloatField(default=0, verbose_name='应收余额')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=256, verbose_name='类名')),
                ('comments', models.CharField(max_length=256, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=256, verbose_name='货物名称')),
                ('amount', models.FloatField(default=1, verbose_name='数量')),
                ('volume', models.FloatField(verbose_name='体积')),
                ('weight', models.FloatField(verbose_name='重量')),
                ('freight', models.FloatField(verbose_name='运费')),
                ('claim_value', models.FloatField(verbose_name='申明价值')),
                ('insurance_rate', models.FloatField(default=1, verbose_name='保价率')),
                ('insurance_fee', models.FloatField(default=0, verbose_name='保价费')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=1024, verbose_name='摘要')),
                ('amount', models.FloatField(verbose_name='支付金额')),
                ('time', models.DateTimeField(verbose_name='制单时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipmentOrder.Customer', verbose_name='客户')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='经办')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=256, verbose_name='发货人')),
                ('from_address', models.CharField(max_length=256, verbose_name='发出地地址')),
                ('sender_contact', models.CharField(max_length=256, verbose_name='发货人联系电话')),
                ('receiver', models.CharField(max_length=256, verbose_name='收货人')),
                ('to_address', models.CharField(max_length=256, verbose_name='到达地地址')),
                ('receiver_contact', models.CharField(max_length=256, verbose_name='收货人联系电话')),
                ('collectFee', models.FloatField(default=0, verbose_name='接货费')),
                ('sendFee', models.FloatField(default=0, verbose_name='送货费')),
                ('paymentOnAccountFreight', models.FloatField(default=0, verbose_name='垫付运费')),
                ('transitFee', models.FloatField(default=0, verbose_name='中转费')),
                ('installFee', models.FloatField(default=0, verbose_name='装卸费')),
                ('storeFee', models.FloatField(default=0, verbose_name='保管费')),
                ('insuranceFee', models.FloatField(default=0, verbose_name='保价费')),
                ('freight', models.FloatField(default=0, verbose_name='运费')),
                ('packingFee', models.FloatField(default=0, verbose_name='包装费')),
                ('totalPrice', models.FloatField(default=0, verbose_name='总价')),
                ('mode', models.CharField(max_length=256, verbose_name='运输方式')),
                ('comments', models.CharField(max_length=256, verbose_name='备注')),
                ('create_date', models.DateField(verbose_name='创建时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(verbose_name='性别')),
                ('birthday', models.DateTimeField(null=True, verbose_name='生日')),
                ('role', models.IntegerField(null=0, verbose_name='角色')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipmentOrder.ShipmentOrder', verbose_name='运送单'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipmentOrder.Payment', verbose_name='付款账单'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shipment_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipmentOrder.ShipmentOrder'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipmentOrder.CustomerClass'),
        ),
    ]
