# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dispatch', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_number', models.IntegerField(default=1, verbose_name='包号')),
                ('goods_name', models.CharField(max_length=256, verbose_name='货物名称')),
                ('amount', models.FloatField(default=0, verbose_name='数量')),
                ('unit_price', models.FloatField(verbose_name='运费单价')),
                ('weight', models.FloatField(verbose_name='重量')),
                ('freight', models.FloatField(verbose_name='运费')),
                ('store_date', models.DateField(null=True, verbose_name='入库日期')),
                ('send_date', models.DateField(null=True, verbose_name='发货日期')),
                ('receive_date', models.DateField(null=True, verbose_name='到达日期')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('dispatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dispatch.DispatchRecord')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=256, verbose_name='发货人')),
                ('from_address', models.CharField(max_length=256, verbose_name='发出地地址')),
                ('sender_contact', models.CharField(max_length=256, verbose_name='发货人联系电话')),
                ('receiver', models.CharField(max_length=256, verbose_name='收货人')),
                ('to_address', models.CharField(max_length=256, verbose_name='到达地地址')),
                ('receiver_contact', models.CharField(max_length=256, verbose_name='收货人联系电话')),
                ('paymentOnAccountFreight', models.FloatField(default=0, verbose_name='垫付运费')),
                ('claimed_value', models.FloatField(default=0, verbose_name='声明价值')),
                ('insurance_rate', models.FloatField(default=1, verbose_name='保价率')),
                ('insurance_fee', models.FloatField(default=0, verbose_name='保价费')),
                ('freight', models.FloatField(default=0, verbose_name='运费')),
                ('packingFee', models.FloatField(default=0, verbose_name='包装费')),
                ('totalPrice', models.FloatField(default=0, verbose_name='总价')),
                ('mode', models.CharField(max_length=256, verbose_name='运输方式')),
                ('volume', models.FloatField(default=0, verbose_name='体积')),
                ('density', models.FloatField(default=0, verbose_name='密度')),
                ('comments', models.CharField(max_length=256, verbose_name='备注')),
                ('create_date', models.DateField(verbose_name='创建时间')),
                ('market', models.CharField(max_length=200, null=True, verbose_name='市场')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.Customer')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='经办')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='shipment_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipmentOrder.ShipmentOrder'),
        ),
    ]
