# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='totalPrice',
            field=models.FloatField(default=0, verbose_name='总价'),
        ),
    ]
