# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentorder',
            name='density',
            field=models.FloatField(default=1, verbose_name='密度'),
        ),
    ]
