# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0002_goods_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='barcode',
        ),
    ]
