# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0002_auto_20171212_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(max_length=18, null=True, verbose_name='身份证号码'),
        ),
    ]
