# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0002_auto_20171208_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentorder',
            name='freight',
            field=models.FloatField(default=0, verbose_name='运费'),
        ),
    ]
