# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0003_auto_20171219_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShipmentOrder.CustomerClass'),
        ),
    ]
