# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0003_auto_20171220_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='insurance_fee',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='insurance_rate',
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='insurance_rate',
            field=models.FloatField(default=1, verbose_name='保价率'),
        ),
    ]
