# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0003_shipmentorder_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentorder',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
