# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0004_auto_20171219_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=256, verbose_name='地址'),
        ),
    ]
