# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0005_auto_20171221_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_class',
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.Customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerClass',
        ),
    ]
