# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipmentOrder', '0006_auto_20171221_0613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='payment_id',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
