# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256, verbose_name='客户名')),
                ('contact_person', models.CharField(max_length=256, verbose_name='联系人')),
                ('contact_number', models.CharField(max_length=256, verbose_name='联系电话')),
                ('identity_number', models.CharField(max_length=18, null=True, verbose_name='身份证号码')),
                ('gender', models.BooleanField(verbose_name='性别')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('comments', models.CharField(max_length=18, verbose_name='备注')),
                ('payable', models.FloatField(default=0, verbose_name='应收余额')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=256, verbose_name='类名')),
                ('comments', models.CharField(max_length=256, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.CustomerClass'),
        ),
    ]
